# An array of sequences 

### List comprehension and genrator expressions



Sequence를 빠르게 만드는방법은 List comprehension을 사용하는 것이다. 


## 1.List comprehensions and readability


Build a list of Unicode codepoints from string

String 으로부터 List of Unicde 빌드하기 

## WS Version

In [14]:

symbols = '##@#!@'

codes = []

for symbol in symbols:
    b= ord(symbol)
    a= codes.append(b)
   
    print(codes)

[35]
[35, 35]
[35, 35, 64]
[35, 35, 64, 35]
[35, 35, 64, 35, 33]
[35, 35, 64, 35, 33, 64]


In [15]:
codes

[35, 35, 64, 35, 33, 64]

## Book Version

In [17]:
symbols = '$@#%%'

codes = [ord(symbol) for symbol in symbols]

codes

[36, 64, 35, 37, 37]

## Cartesian Products

카르테시안 Products


![220px-cartesian_product_qtl1 svg](https://user-images.githubusercontent.com/11300712/42076530-67b83fac-7b2a-11e8-904b-abd7b8c71731.png)



In [25]:
colors = ['black', 'white']

sizes = ['s','m','l']


for color in colors : 
    for size in sizes:
            print((color,size))

('black', 's')
('black', 'm')
('black', 'l')
('white', 's')
('white', 'm')
('white', 'l')


In [41]:
cartesian= [(color,size) for color in colors for size in sizes]

In [42]:
cartesian

[('black', 's'),
 ('black', 'm'),
 ('black', 'l'),
 ('white', 's'),
 ('white', 'm'),
 ('white', 'l')]


## 2.Tuple은 단지 변하지 않는 list가 아니다.

### 2.1 Tupes as records

Tuple은 records를 hold한다. 


#### 문제 : tuple을 records로 사용해보세요.  

주의 : tuple 을 sorting하게 되면 information이 손실된다. 
왜냐하면 각 data는 tuple에 의해서 주어졌기 때문이다.


##### 1. LAX의 Latitude and Longtitude 

lax_coordinates = (33.9425, - 118.408056)

#####  2. 도쿄의 데이터
city = Tokyo

year = 2003

pop = 32450

chg = 0.66

area = 8014

##### 3. 

traveler_ids = [('usa', '31195855'), ('bra', 'ce342567'), ('esp','xda205856')]

##### * 다음과 같이 바꿔보세요. 

bra/ce342567

esp/xda205856

usa/31195855


In [48]:
lax_coordinates = (33.9425, -118.408056)

city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)

traveler_ids = [('usa', '31195855'), ('bra', 'ce342567'), ('esp','xda205856')]


In [62]:
for passport in sorted(traveler_ids):
    print('%s/%s'% passport)

bra/ce342567
esp/xda205856
usa/31195855


### 2.2 Tuple unpacking 두번째 방법



lax_coordinates = (33.9425, - 118.408056)

latitude 와 coordinates를 분리해보세요. 

In [78]:
lax_coordinates = (33.9425, - 118.408056)

In [79]:
latitude, longitude=lax_coordinates 


In [80]:
latitude

33.9425

In [81]:
longitude

-118.408056

In [82]:
a,b =latitude, longitude

In [83]:
a

33.9425

In [84]:
b

-118.408056

### 2.3 Tuple unpacking 세번째 방법

##### divmod
divmod(a, b)는 2개의 숫자를 입력으로 받는다. 그리고 a를 b로 나눈 몫과 나머지를 튜플 형태로 리턴하는 함수이다.




In [89]:
divmod(10,2)

(5, 0)

##### divmod로 생성된 튜플을 unpacking하는 방법은 다음과 같다.

In [90]:
divmod(20,8)


(2, 4)

In [97]:
t = (20,8)
t

(20, 8)

In [98]:
divmod(*t)

(2, 4)

In [ ]:
qutient, remainder = divmod(*t)

print(qutient)
print(remainder)

### 2.4 * 을 사용하기

In [101]:
range(5)

range(0, 5)

In [104]:
a,b, *rest = range(5)

print(a)
print(b)
print(*rest)

0
1
2 3 4


In [106]:
a,b,rest

(0, 1, [2, 3, 4])

# 3. Slicing

List, tuple, stre 그리고 모든 sequence type에서 파이썬은 slicing operationg을 제공한다. 

### 3.1

In [115]:
l= [10,20,30,40,50,60]

print(l[:2])

print(l[2:])

[10, 20]
[30, 40, 50, 60]


### 3.2 Object를 slice


In [126]:
my_name = "wonseokjung"

print(my_name[:3])
#skipping 
print(my_name[::2])
#backward skipping
print(my_name[::-1])

won
wnekug
gnujkoesnow


## 4. Multi-dimensional slicing and ellipsis


In [139]:
l= list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [140]:
l[2:5] = 20,30

l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [141]:
del l[2:6]
l

[0, 1, 7, 8, 9]

### 4.1 Using + and * with sequences 

In [142]:
l = [1,2,3]

l *5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [144]:
5*'won'

'wonwonwonwonwon'

### 4.2 Building lists of lists

In [151]:
star = ["***" for i in range(10)]

print(star)

star2 = [["*"] for i in range(10)]

print(star2)

['***', '***', '***', '***', '***', '***', '***', '***', '***', '***']
[['*'], ['*'], ['*'], ['*'], ['*'], ['*'], ['*'], ['*'], ['*'], ['*']]


### 4.3 다른 방법으로 list를 만들고, 리스트 안의 내용 변환

In [157]:
another_list = [["*"]*5] * 5

another_list

[['*', '*', '*', '*', '*'],
 ['*', '*', '*', '*', '*'],
 ['*', '*', '*', '*', '*'],
 ['*', '*', '*', '*', '*'],
 ['*', '*', '*', '*', '*']]

In [158]:
another_list[1][2]= 3

another_list



리스트에 '*' 을 만들어 추가

In [164]:
b=[]

for i in range(10):
    a= ["*"]
    b.append(a)
    
b

[['*'], ['*'], ['*'], ['*'], ['*'], ['*'], ['*'], ['*'], ['*'], ['*']]

## 5.Augmented assignment with sequences 

operators += , *= 사용

In [185]:
l =[1,2,3]
# id() = memory location
id(l)


4375681160

In [202]:
t=(1,2,3)
id(t)

4374314440

In [203]:
t*=2
print(t)
print(id(t))

(1, 2, 3, 1, 2, 3)
4374250216


### 5.1 A += Assignment puzzler

In [208]:
t=(1,2,[30,40])

print(t)

t[2]+=[10,50]

print(t)

(1, 2, [30, 40])


TypeError: 'tuple' object does not support item assignment

In [209]:
t

(1, 2, [30, 40, 10, 50])

### 6. list.sort and the sorted built-in function

In [12]:
company = ['Samsung', 'LG', 'Apple']

print("campany:",company)

#sort
print("sorted:",sorted(company))

#순서를 거꾸로 sort
print("reversed sorted", sorted(company, reverse=True))

#길이로 sort 
print("length sort:",sorted(company, key=len))

#len with reverse

print("len and reverse sort", sorted(company, key=len, reverse = True))

# sort된 순서로 company 바꾸기
company.sort()

print(company)

campany: ['Samsung', 'LG', 'Apple']
sorted: ['Apple', 'LG', 'Samsung']
reversed sorted ['Samsung', 'LG', 'Apple']
length sort: ['LG', 'Apple', 'Samsung']
len and reverse sort ['Samsung', 'Apple', 'LG']
['Apple', 'LG', 'Samsung']


### 7.Managing ordered sequences with bisect

In [14]:
import bisect 
import sys

HAYSTACK = [1,4,5,6,8,12,15,20,21,23,23,26,29,30]

NEEDLES = [0,1,2,5,8,10,22,23,29,30,31]

ROW_FMT = '{0:2d} @ {1:2d} {2}{0:<2d}'

def demo(bisct_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, needle)
        offset = position * 'L'
        print(ROW_FMT.format(needle, position, offset))

        
if __name__ == '__main__':
    if sys.argv[-1] == 'left':
        bisect_fn = bisect.bisect_left
    else: 
        bisect_fn = bisect.bisect
        
    print('DEMO', bisect_fn.__name__)
    print('haystack -> ', ''.join('%2d' % n for n in HAYSTACK))
    demo(bisect_fn)

DEMO bisect
haystack ->   1 4 5 6 8121520212323262930
31 @ 14 LLLLLLLLLLLLLL31
30 @ 14 LLLLLLLLLLLLLL30
29 @ 13 LLLLLLLLLLLLL29
23 @ 11 LLLLLLLLLLL23
22 @  9 LLLLLLLLL22
10 @  5 LLLLL10
 8 @  5 LLLLL8 
 5 @  3 LLL5 
 2 @  1 L2 
 1 @  1 L1 
 0 @  0 0 


In [16]:
def grade(score, breakpoints = [90,70,80,90], grades = 'FDCBA'):
    i = bisect.bisect(breakpoints, score)
    return grades[i]


In [21]:
[grade(score) for score in [33,99,77,70,89,90,100]]

['F', 'A', 'C', 'C', 'B', 'A', 'A']

### 7.1 Inserting with bisect.insrot

In [23]:
import bisect
import random

size = 7

random.seed(219)

wonseok_list = []

for i in range(size):
    new_item=random.randrange(size * 2)
    bisect.insort(wonseok_list, new_item)
    print('%2d ->'% new_item,wonseok_list)

11 -> [11]
10 -> [10, 11]
 5 -> [5, 10, 11]
 8 -> [5, 8, 10, 11]
 0 -> [0, 5, 8, 10, 11]
 5 -> [0, 5, 5, 8, 10, 11]
11 -> [0, 5, 5, 8, 10, 11, 11]


### 7.3 Array

In [8]:
from array import array

from random import random

"""
  - 'r' : 읽기 전용
  - 'w' : 쓰기 전용
  - 'a' : 파일 끝에 추가(쓰기 전용)
  - 'r+' : 읽고 쓰기
  - 'w+' : 읽고 쓰기(기존 파일 삭제)
  - 'a+' : 파일 끝에 추가(읽기도 가능)
  - 'rb' : 이진 파일 읽기 전용
  - 'wb' : 이진 파일 쓰기 전용
  - 'ab' : 이진 파일 끝에 추가(쓰기 전용)
  - 'rb+' : 이진 파일 읽고 쓰기
  - 'wb+' : 이진 파일 읽고 쓰기(기존 파일 삭제)
  - 'ab+' : 이진 파일 끝에 추가(읽기도 가능)
"""

floats = array('d',(random () for i in range(10**7)))


print("Last :" ,floats[-1])

fp = open('floats.bin', 'wb')

floats.tofile(fp)

fp.close()

floats2 = array('d')

fp = open('floats.bin', 'rb')

floats2.fromfile(fp, 10**7)

fp.close()

print(floats2[-1])

print(floats==floats2)

Last : 0.9696652206381505
0.9696652206381505
True


### 8. Memory views

In [19]:
import array

numbers = array.array('h',[-2,-1,0,1,2])

memv = memoryview(numbers)

print(len(memv))

print(memv[0])

memv_oct=memv.cast('B')

print(memv_oct)

print(memv_oct.tolist())

print(numbers)

5
-2
[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]
array('h', [-2, -1, 0, 1, 2])


### 9. Numpy and  Scipy

In [29]:
import numpy as np

a= np.arange(12)

print(a)

print(type(a))

print(a.shape)

a.shape=3,4

print(a)


print(a[2,1])


print(a[:,1])

print(a.transpose())

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
9
[1 5 9]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


#### 9.1 High-level operations using numpy

In [52]:

import numpy as np

np.savetxt('ws_test.txt' ,np.arange(100))

floats = np.loadtxt('ws_test.txt')

print(floats)
print("---")
print(floats[-3:])



[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.  29.
  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.  43.  44.
  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.  57.  58.  59.
  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.  71.  72.  73.  74.
  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.  85.  86.  87.  88.  89.
  90.  91.  92.  93.  94.  95.  96.  97.  98.  99.]
---
[ 97.  98.  99.]


### 10. Deques and other queues 

In [71]:
from collections import deque




dq = deque(range(10), maxlen=10)

print(dq)

print(deque(range(100),maxlen=10))

dq.rotate(-4)

print(dq)

dq.appendleft(-1)

print(dq)

dq.extend([10,20,30])

print(dq)

dq.extendleft([12031,123,1235])

print(dq)

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
deque([90, 91, 92, 93, 94, 95, 96, 97, 98, 99], maxlen=10)
deque([4, 5, 6, 7, 8, 9, 0, 1, 2, 3], maxlen=10)
deque([-1, 4, 5, 6, 7, 8, 9, 0, 1, 2], maxlen=10)
deque([6, 7, 8, 9, 0, 1, 2, 10, 20, 30], maxlen=10)
deque([1235, 123, 12031, 6, 7, 8, 9, 0, 1, 2], maxlen=10)
